In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/aryashah2k/sample-students-grades-dataset-tutorial-notebook/grades.csv

In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

df = pd.read_csv('/kaggle/input/datasets/aryashah2k/sample-students-grades-dataset-tutorial-notebook/grades.csv')
df

    exam  student_id  grade
0      1           1   86.0
1      1           2   65.0
2      1           3   70.0
3      1           4   98.0
4      1           5   89.0
5      1           6    NaN
6      1           7   75.0
7      1           8   56.0
8      1           9   90.0
9      1          10   81.0
10     2           1   79.0
11     2           2   60.0
12     2           3   78.0
13     2           4   75.0
14     2           5    NaN
15     2           6   80.0
16     2           7   87.0
17     2           8   82.0
18     2           9   95.0
19     2          10   96.0
20     3           1   78.0
21     3           2   80.0
22     3           3   87.0
23     3           4    NaN
24     3           5   89.0
25     3           6   90.0
26     3           7  100.0
27     3           8   72.0
28     3           9   73.0
29     3          10   75.0
30     4           1    NaN
31     4           2   80.0
32     4           3   81.0
33     4           4   82.0
34     4           5   83.0
35     4           6   84.0
36     4           7   85.0
37     4           8   86.0
38     4           9   87.0
39     4          10   88.0
40     5           1   90.0
41     5           2    NaN
42     5           3   91.0
43     5           4   92.0
44     5           5   93.0
45     5           6   94.0
46     5           7   95.0
47     5           8   96.0
48     5           9   97.0
49     5          10   98.0

In [3]:
df.isnull().mean()

exam          0.0
student_id    0.0
grade         0.1
dtype: float64

In [4]:
df['grade'] = df['grade'].fillna(df['grade'].mean())

In [5]:
df

    exam  student_id       grade
0      1           1   86.000000
1      1           2   65.000000
2      1           3   70.000000
3      1           4   98.000000
4      1           5   89.000000
5      1           6   84.177778
6      1           7   75.000000
7      1           8   56.000000
8      1           9   90.000000
9      1          10   81.000000
10     2           1   79.000000
11     2           2   60.000000
12     2           3   78.000000
13     2           4   75.000000
14     2           5   84.177778
15     2           6   80.000000
16     2           7   87.000000
17     2           8   82.000000
18     2           9   95.000000
19     2          10   96.000000
20     3           1   78.000000
21     3           2   80.000000
22     3           3   87.000000
23     3           4   84.177778
24     3           5   89.000000
25     3           6   90.000000
26     3           7  100.000000
27     3           8   72.000000
28     3           9   73.000000
29     3          10   75.000000
30     4           1   84.177778
31     4           2   80.000000
32     4           3   81.000000
33     4           4   82.000000
34     4           5   83.000000
35     4           6   84.000000
36     4           7   85.000000
37     4           8   86.000000
38     4           9   87.000000
39     4          10   88.000000
40     5           1   90.000000
41     5           2   84.177778
42     5           3   91.000000
43     5           4   92.000000
44     5           5   93.000000
45     5           6   94.000000
46     5           7   95.000000
47     5           8   96.000000
48     5           9   97.000000
49     5          10   98.000000

In [6]:
X = df[['exam']]   # input feature
y = df[['grade']]  # correct target column

model = LinearRegression()
model.fit(X, y)

predicted_score = model.predict(X)
mae = mean_absolute_error(y,predicted_score)
mse = mean_squared_error(y,predicted_score)
rmse = np.sqrt(mse)

print(mae)
print(mse)
print(rmse)


new_prediction = model.predict([[7]])
print("Predicted Score {new_pred} hour ", new_prediction)

6.483555555555557
71.40835555555556
8.450346475473983
Predicted Score {new_pred} hour  [[96.01777778]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(